# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c99eed22e8d100048f615224c7689133d0a276f191e5f13b4342432051f7cd5fd45840fb4745e06175142e5a9053f2a766bb3c0f722ec28c10bddf395f61de

test:
  secret_key_base: 0d72cc563a7789d556159d8ce348e41a291a5dec6ac3f17229d7206930bcf9f178a922d2383720d7bf02e920f7aaadb4de2060fc6fed737ca28d86f9f218de11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
